### ISSUE TITLE
Cannot create a field without error popup

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#108]
Creating any field in the Field Manager will give me the following error when I click create:
![image](https://cloud.githubusercontent.com/assets/22599103/24667890/2cf2a076-1922-11e7-8555-e6d2b50399f7.png)

However, it still creates the entry in the database:
![image](https://cloud.githubusercontent.com/assets/22599103/24667958/644595d8-1922-11e7-8c17-253bbb8f587a.png)

**Comment by ShawnClake** [comment]
Fixed. The problem occurred because the FieldManager doesn't have validation yet, but the Field model was expecting a Validator object in return.
