### ISSUE TITLE
Deleting a Group that has a Role in it creates an error

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#110]
Deleting a Group that has a role in it produces this error:

![image](https://cloud.githubusercontent.com/assets/22599103/24668981/da2a39f4-1925-11e7-882a-db37b2a09963.png)

Once clicking OK, the group 'looks' like it still exists with the Role in the group:
![image](https://cloud.githubusercontent.com/assets/22599103/24669056/23c2d42c-1926-11e7-9bfe-d57505e823db.png)

However, clicking on a different group will cause the group to disappear and the Role to be placed in the list of Roles on the left.

![Uploading image.png…]()

**Comment by ShawnClake** [comment]
This is now fixed. The problem occurred because the session wasn't properly being reset when deleting a group. As well, added error checking for when no groups exist.
