### ISSUE TITLE
Default group didn't work when registered

### ISSUE THREAD

**Issue by Amn37ia** [ShawnClake/UserExtended#115]
im forgeting to ask this but, i've set default group to "user", but everytime i registered account, that account didn't automaticaly have default group, is that my mistake or there's a bug in plugin, if there's a way to put it manualy please give me solution.

**Comment by QuinnBast** [comment]
Confirmed this is a bug. I changed the default group and attempted to register a new user and got the following error:

![image](https://cloud.githubusercontent.com/assets/22599103/25396567/474fd87c-29a2-11e7-8704-1ac16b117a03.png)

**Comment by QuinnBast** [comment]
After running a refresh and switching to our current development cycle this error has been fixed and will be fixed in the next update.

**Comment by ShawnClake** [comment]
I've also tested this on the 2.2.00 code which should release in a few days, this problem has been fixed. Thanks for the bug report!
