### ISSUE TITLE
Error trying to access the Modules Tab

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#116]
Clicking on the Modules tab gives the following error:

![image](https://cloud.githubusercontent.com/assets/22599103/25397999/9df062c8-29a7-11e7-9b68-7f6f8a7c1b21.png)

I think this error is also relating to this bug:
![image](https://cloud.githubusercontent.com/assets/22599103/25398269/9be68880-29a8-11e7-97b5-b506c47e42db.png)

**Comment by ShawnClake** [comment]
@QuinnBast  Is this resolved?

**Comment by QuinnBast** [comment]
Yes
