### ISSUE TITLE
Cant find .../Route/fields.yaml, in Backend\Behaviors\FormController." on line 63

### ISSUE THREAD

**Issue by mnvx** [ShawnClake/UserExtended#124]
When I press "+ Track Another Route" on page backend/clake/userextended/routes/create
I have next error message:

> "Не удалось найти конфигурационный файл /var/www/zabor/plugins/clake/userextended/models/Route/fields.yaml, ожидаемый для Backend\Behaviors\FormController." on line 63 of /var/www/zabor/modules/system/traits/ConfigMaker.php

**Comment by ShawnClake** [comment]
I'm fairly certain this has been fixed as a result of pull request #125
