### ISSUE TITLE
Add better feedback when errors occur

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/UserExtended#24]
Many errors can occur and currently do not return any feedback.

Add feedback to situations which can occur in:
* Registration
* Logging in
* Logging out
* Roles/Groups updating, creating
* Profile visibility
* Commenting
* Setting changing

**Comment by ShawnClake** [comment]
Pushing this back to a later release as I will need to work on a plugin wide error handler for consistency

**Comment by QuinnBast** [comment]
Javascript now validates:
Registration, Sign-In, Account Settings changes, Login, and Logout.

**Comment by ShawnClake** [comment]
Completed:
* Logout
* Login
* Account Settings
* Registration

In-Progress:
* Roles/Groups updating, creating

Still Required:
* Profile visibility
* Commenting

**Comment by ShawnClake** [comment]
Pushing this issue back another release as we've dealt with the high priority points.

**Comment by ShawnClake** [comment]
All of the points on this list have been hit
