### ISSUE TITLE
Datastrucure Plugin not included

### ISSUE THREAD

**Issue by bkrajendra** [ShawnClake/UserExtended#3]
Hey @ShawnClake 
I guess you forgot to mention about Data Structure Plugin.
It need to be installed before using UserExtended

**Comment by ShawnClake** [comment]
This was not the intention. While I do have a data structures plugin, which currently isn't on the October marketplace, it was not supposed to be a dependency.

I have fixed the problem and published another update. Thanks for heads up.

**Comment by ShawnClake** [comment]
@bkrajendra 

I found the actual source of this problem. Currently, utilizing the searching or random user set abilities will cause this error to appear. I will try to publish the Data structure plugin to the October Marketplace and add the dependency as soon as I can.

**Comment by bkrajendra** [comment]
I was knowing this .. i already fixed this by downloading your Datastructure plugin from ur repo.
Thats why i asked you about "forgot to mention"
Its ok..! your idea is very good and this can be very interesting project. Keep up the good work. I'll contribute as and when I get time.

**Comment by ShawnClake** [comment]
Yea, you're right. Thank you for the feedback and the bug catch! 

The data structures plugin was approved yesterday onto the October marketplace: http://octobercms.com/plugin/clake-datastructures
