### ISSUE TITLE
Add exceptions to User Extended

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/UserExtended#30]
Throw exceptions at key points in the operation of UserExtended.

Key points which can't fail (but not limited to):
* Module registration
* User registration
* User login

**Comment by QuinnBast** [comment]
Javascript now throws proper errors when a user does not give valid input. However, if the user disables their javascript then there is no feedback on problems that happen serverside. Not certain how to check for server-side errors at the moment.

**Comment by ShawnClake** [comment]
Exceptions still aren't thrown for Module Registrations. This isn't a high priority feature though. I'll keep this open and change the deadline for a future date.

Instead of exceptions for logging in and registration, I've decided just to return them to their same page with some flash messages.
