### ISSUE TITLE
Add user settings (dynamic) to the backend user editor/viewer

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/UserExtended#31]
Add a tab to backend->user where we can view dynamic user settings and update the dynamic user settings.

Also, on user create, add a tab to create user settings which are marked as createable.

**Comment by ShawnClake** [comment]
@QuinnBast 

Is there more that needs to be done for this?

**Comment by QuinnBast** [comment]
I have 2 custom fields in Field Manager that are "Editable" and "Enabled" But they do not show up in the "Update User" tab, are they supposed to?

**Comment by ShawnClake** [comment]
@QuinnBast Unfortunately I did try to see if I could get that to work, but because the fields are stored as JSON, it won't know how to save it. In other words, I can make it so the fields appear on the form, but it'll error when trying to persist.

For now, this isn't doable until we find another work around

**Comment by QuinnBast** [comment]
Alright, otherwise the User backend looks great!

**Comment by ShawnClake** [comment]
I'm going to mark this as pushed back and then we'll finish it at a later time when we can find a good work around.
