### ISSUE TITLE
Have a problem with clake userextended and last october release 3.9.6

### ISSUE THREAD

**Issue by queengab** [ShawnClake/UserExtended#55]
Hi,

i've installed this usefull plugin on my local machine with vagrant environment.
But when i click on Role Manager have this error:

`
syntax error, unexpected 'for' (T_FOR)
../plugins/clake/userextended/controllers/roles.php line 57
`
The line:
$groupRoles = RoleManager::for($this->vars['selectedGroup']->code);

Bye
gab

**Comment by ShawnClake** [comment]
Hi Gabe, thanks for the bug report. I will look more into this and hopefully patch a fix for the next release.

- Shawn

**Comment by ShawnClake** [comment]
Hi Gab,

It's looking like my use of the PHP keyword 'for' is what was causing this error. I've updated the plugin which replaces all the functions named 'for' with 'with'.

I'm hoping this will fix the problem.

**Comment by queengab** [comment]
Hi Shawn thanks for the support!
I will be your beta tester! :)

So i tried that change and it works!
I had the stable version installed on my october test website via plugin manager, so, in order to had plugin work, i do this steps:

Change these files as you said in the commit report
classes/RoleManager.php
classes/UserGroupManager.php
classes/UserRoleManager.php
components/User.php
controllers/Roles.php

And editthe file (existing in the model directory):
models/Roles.php

And create this file
models/Role.php da creare non esiste nella stable release

Clearly if you download the dev_release from github and install it with php:artisan all works well!!

Thanks very much! This plugin is a fantastic job! I think all community appreciate your work.

Bye
Gab

**Comment by ShawnClake** [comment]
Thank you for the kind words and the feedback. I'm glad to hear it's working properly!

Thanks,
Shawn
