### ISSUE TITLE
Restrict user access to some front.end page

### ISSUE THREAD

**Issue by queengab** [ShawnClake/UserExtended#56]
Hi,

i'm trying to restrict gruops permissions, adding restricted access for some front-end pages.
How, if the user gropus component is depracated?

Thanks yet!
gab

**Comment by ShawnClake** [comment]
Hi Gab,

This functionality was moved to the User component. An outline of the component can be found here: https://github.com/ShawnClake/UserExtended/wiki/%5BComponent%5D-User

Hopefully that helps!

Thanks,
Shawn

**Comment by ShawnClake** [comment]
Hey Gab, I'm going to close this now. Hopefully you found the information you needed, if not, feel free to reopen it. 

Thanks,
Shawn
