### ISSUE TITLE
Namespace initialization errors

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#57]
When setting up the plugin for first use this error pops up:
![image](https://cloud.githubusercontent.com/assets/22599103/23471347/a0fddee6-fe6e-11e6-827b-e7bc0655f9ee.png)

As a work-around for this issue comment out "use Clake\Userextended\Models\UserExtended;" line in the following files:
classes/TimezoneHandler.php
classes/UserSettingsManager.php
classes/UserUtil.php

**Comment by ShawnClake** [comment]
Potential fix:
Replace use lines with fully qualified namespace names where needed.

Backup plan:
Add aliases to use lines

**Comment by ShawnClake** [comment]
@QuinnBast Has this been fixed? I'm not sure if there were any remaining trouble spots

**Comment by QuinnBast** [comment]
The newest update gives me no more errors with namespace includes
