### ISSUE TITLE
Cannot access Role Manager without any accounts

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#58]
Accessing Role Manager without an account brings up the following error:
![image](https://cloud.githubusercontent.com/assets/22599103/23471599/8952aa14-fe6f-11e6-871b-555860c5e5da.png)

**Comment by ShawnClake** [comment]
@QuinnBast This has been fixed if I mistaken?

**Comment by QuinnBast** [comment]
I believe so
