### ISSUE TITLE
Accessing "Acount Settings" page while not logged in shows a blank page

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#59]
![image](https://cloud.githubusercontent.com/assets/22599103/23471926/b43bdb96-fe70-11e6-9a79-3719a2506f88.png)

Going to add an alert message that tells the user they are not logged in when accessing the page.

**Comment by ShawnClake** [comment]
Look into utilizing flash data if possible:
http://octobercms.com/docs/services/response-view#redirect-flash-data

**Comment by QuinnBast** [comment]
I believe this is resolved? It doesn't redirect the user but it gives them information about what is going on now.

**Comment by ShawnClake** [comment]
I haven't tested it myself, but I'll take your word for it. Is this true of the latest commit in which I move it to an external CSS file?

**Comment by QuinnBast** [comment]
Yes the external CSS works
