### ISSUE TITLE
Creating an account makes unnessecary popup

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#60]
When registering for an account I get the following popup:

![image](https://cloud.githubusercontent.com/assets/22599103/23473586/5fde20c6-fe76-11e6-9129-c324a9e3bf18.png)

However, it creates the account and I am able to login.

**Comment by ShawnClake** [comment]
@QuinnBast Is this still broken?

**Comment by QuinnBast** [comment]
Yes and no. The popup still shows even after adding a session however, the popup is different:

![image](https://cloud.githubusercontent.com/assets/22599103/23478698/c0303610-fe87-11e6-897b-d43a19183e2c.png)

**Comment by ShawnClake** [comment]
@QuinnBast Try pulling in the latest commits and see if that helps

**Comment by QuinnBast** [comment]
The latest commit resolved the issue
