### ISSUE TITLE
User Session Error

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#61]
When logged in to an account, clicking "register" brings up the following error

![image](https://cloud.githubusercontent.com/assets/22599103/23473738/e84285ec-fe76-11e6-99b3-a8c68525f404.png)

**Comment by QuinnBast** [comment]
Update: I have logged out of the "test" account and went to register for a new account now that I was logged out and I get the same error. This is an issue with the "id" variable in the code as it is saving my session for some reason

**Comment by QuinnBast** [comment]
Update: This issue is now also happening while logged in and trying to view account settings

**Comment by ShawnClake** [comment]
@QuinnBast Is this still broken or did adding a session component solve it?

**Comment by QuinnBast** [comment]
Adding a session fixed some of the problem. 
Changing UserUtils like 156 to have this:
return \Clake\Userextended\Models\UserExtended::where('id', $id)->first();
alongside the commented out line 5:
//use Clake\Userextended\Models\UserExtended;

Have resolved all issues
