### ISSUE TITLE
Signing up doesn't validate form inputs

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#63]
Entering a name that is all numbers is valid input.
Entering a phone number that is all letters is valid input.
Entering a name/phone that is a mix of numbers and letters is valid input.

May be prone to SQL injection.

**Comment by ShawnClake** [comment]
Good point. These fields are cleaned by default via October's DB system, but other validation should be fixed.

Take a look in /config/user_settings.yaml and add validation rules (to each settings validation property) according to:
http://octobercms.com/docs/services/validation#available-validation-rules

Probably best to set each one as encrypted as well.

**Comment by ShawnClake** [comment]
@QuinnBast I did a bit of a refactor of how the Account component works. I moved a lot of its logic to classes/UserManager.php. The main reasoning was to enforce DRY for when I add an API for programmatically registering users etc.

This isn't tested yet, so I might've broken registration/logging in, but the validation stuff is now done in classes/UserManager.php

**Comment by QuinnBast** [comment]
Required form inputs are now validated with javascript. Things like "cellphone" are user-controlled input fields will be unable to be verified unless the creator of the fields is able to select what type of input it should be validated as. If ther user is able to select what it should be validated as (ie. number, date, phone, etc. Let me know what field that is while it is in the {{settings}} loop and I can work on adding extra validation for these inputs via javascript. However, if that is not currently a feature this issue can be closed.

**Comment by ShawnClake** [comment]
It would be hard to validate it the way it currently is, instead I am going to try and setup flash message feedback from the server side.

**Comment by ShawnClake** [comment]
@QuinnBast 

> It would be hard to validate it the way it currently is, instead I am going to try and setup flash message feedback from the server side.

This needs testing and then this issue can be closed.

**Comment by QuinnBast** [comment]
No flash message came up when registering an account with firstname+lastname 123456 and phone+cell as hello

**Comment by ShawnClake** [comment]
Migrated to use October's data tag validation. I had no idea this existed until yesterday.

Pros:
* Works out of the box
* Simple and fast to setup
* Stable

Cons:
* Not dynamic or real time
* The error messages come from the validation class and can sometimes be a bit cryptic

This validation works to some degree. It is more stable and utilizes every single type of validation which the backend validation can use, but the Flash messages still appear to be somewhat broken.

An optimal solution would be to add a dynamic JS layer over top using something like Parsley JS.

I'm going to move this issue to be due for a future release as the dynamic layer is lower priority.
