### ISSUE TITLE
Role Manager Delete button not responsive

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#64]
My screen size causes problems with displaying the delete button in the role manager. Screen size 1200x319 through 1660x319 have visible issues with the delete button.

![image](https://cloud.githubusercontent.com/assets/22599103/23480652/527d1104-fe8e-11e6-92f0-f25ab777dff2.png)

**Comment by ShawnClake** [comment]
This is a feature October built in to tool bars. I wish it were more obvious, but if you click on that row and drag to the sides, it actually scrolls it and the rest of the delete button becomes visible again.
