### ISSUE TITLE
Validate Role/Group code fields when creating roles/groups

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#66]
I have created 2 roles, a role called "admin 1" and a role called "friend 1":

![image](https://cloud.githubusercontent.com/assets/22599103/23482339/53391be6-fe94-11e6-996e-2e630c09d4cb.png)

I assign "admin 1" to the admin group easily:

![image](https://cloud.githubusercontent.com/assets/22599103/23482353/67b3998e-fe94-11e6-8d0a-b3f21443a1f9.png)

I switch to the friend group to add the "friend 1" role to the friend group. The Friend group however, doesn't display all the roles I have created:

![image](https://cloud.githubusercontent.com/assets/22599103/23482380/892a0e9a-fe94-11e6-8f82-1ada7dbdf7b9.png)

Nontheless, I go to assign "friend 1" to my friend group but it assigns index 1 of the list and finds "admin 1" (which is not displayed):

![image](https://cloud.githubusercontent.com/assets/22599103/23482449/bc4356a6-fe94-11e6-9c62-04ddca214f49.png)

Switching back to admin, the admins are no longer assigned "admin 1" (expected behavior)

![image](https://cloud.githubusercontent.com/assets/22599103/23482477/d7043d84-fe94-11e6-8fc2-1405b7e3795b.png)

But the same thing happens; assigning "friend 1" to admins will assign it index 1 and assign "admin 1"

![image](https://cloud.githubusercontent.com/assets/22599103/23482509/f6c93ad4-fe94-11e6-9ee3-aa64205d5685.png)

Thus I have to assign the roles bottom-up. Clearing all of the roles I have assigned to the groups, "friend 1" is the last role I have created so if I assign "friend 1" first it should assign the "friend 1" role:

![image](https://cloud.githubusercontent.com/assets/22599103/23482632/65548e36-fe95-11e6-8f77-add7c153a6ec.png)

Huh. Nevermind. It still assigns "admin 1"

**Comment by ShawnClake** [comment]
When creating roles and groups, they must have a valid and unique code given to them to differentiate them. There should be validation for this, and the Role/Group creation should fail if no code is given.

**Comment by ShawnClake** [comment]
The popup form really should have more text to make it clear what code is, the MySQL table should have the unique modifier applied to the column, and there should be validation

**Comment by QuinnBast** [comment]
Adding a "code" to each role fixed this issue and properly allows me to assign user roles to groups.

**Comment by ShawnClake** [comment]
The Role is validated now, however feedback isn't yet provided. It'll simply not modify the DB and not break the entire application.

**Comment by ShawnClake** [comment]
Create/Update forms now have proper help text for describing what the fields require.

Potential future upgrades:
* JS onChange validation.
* JS onChange slugify $name -> $code
* Disabling of the save button unless the form passes JS validation
* A list of validation problems with the forms by utilizing feedback given by returning $validator.

Forms of interest (/controllers/roles):
* _create_group_form.htm
* _create_role_form.htm
* _update_group_form.htm
* _update_role_form.htm

Potential solution:
Create another partial (maybe _validate_forms_js.htm) and create all the JS in there. Then, use the PHP makePartial function to include this partial on to many other partials, in particular the 4 listed above.
More info: http://octobercms.com/docs/backend/views-partials#partials

@QuinnBast Would you like to test the waters of October by working on those?

**Comment by QuinnBast** [comment]
Still unable to assign a role to a group. When clicking the arrow I get a confirmation message, clicking 'ok' doesn't assign or deassign the group.

**Comment by QuinnBast** [comment]
Latest push fixed this issue. I am currently working on validating the forms with javascript. Will close the issue when I push validation.
