### ISSUE TITLE
Clicking the blue text under "role" in the role manager creates an error

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#67]
Clicking the links for the roles as indicated here:

![image](https://cloud.githubusercontent.com/assets/22599103/23482842/1b9dcb94-fe96-11e6-8cb8-07182f82b800.png)

Will bring up the following error:

![image](https://cloud.githubusercontent.com/assets/22599103/23483035/d9526fbe-fe96-11e6-858c-44c084fe4764.png)

**Comment by ShawnClake** [comment]
@QuinnBast Also probably a consequence of no code being given

**Comment by QuinnBast** [comment]
Nada. Giving each role a code manually in the database still shows this error when clicking the blue links

**Comment by QuinnBast** [comment]
New commit results in a new error:

![image](https://cloud.githubusercontent.com/assets/22599103/23483673/8ad8ee5a-fe99-11e6-8bb6-23a0ac2693b5.png)

Once clicking "ok" on the error box I am stuck with a spinning loading symbol that won't go away

![image](https://cloud.githubusercontent.com/assets/22599103/23483690/9f63e118-fe99-11e6-83e8-13ac97739d39.png)

**Comment by ShawnClake** [comment]
@QuinnBast I either fixed this or catastrophically broke role editing altogether :P.

**Comment by QuinnBast** [comment]
I still get the same error as pictured above

**Comment by QuinnBast** [comment]
Still infinitely loading :( No longer shows the error message about line 7 though!

**Comment by ShawnClake** [comment]
@QuinnBast What happens if you try to edit a group or edit a role assigned to a group?

**Comment by Teranode** [comment]
Try changing UE.Validator to something else without the dot notation cause UE isnt defined anywhere within the js files.

**Comment by ShawnClake** [comment]
> Try changing UE.Validator to something else without the dot notation cause UE isnt defined anywhere within the js files.

This notation was added yesterday, but the bug has been occurring for longer than that, so I don't think that's the cause of the issue. I did forget to define UE as you said though, and I've fixed that in a commit. Thanks for pointing that out!

**Comment by Teranode** [comment]
ill see if i can find anything

**Comment by QuinnBast** [comment]
Found the issue! The problem was caused by incorrect anchor properties (ie. copy and paste) which caused the popup to not load because it was not being passed the correct data.

@Teranode is correct with UE being undefined and after your commit, UE is still undefined. However the use of UE is for javascript validation so this issue can be closed!
