### ISSUE TITLE
Flesh out the column and list definitions for models

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/UserExtended#80]
These models need their column and fields definitions filled out:
* Comment
* Friend
* Timezone
* Userextended
* Usergroup

The folders must also be renamed to not be pluralized. They must match the model name.

**Comment by ShawnClake** [comment]
@QuinnBast 

For assistance with fields.yaml
http://octobercms.com/docs/backend/forms#form-fields

For assistance with columns.yaml
http://octobercms.com/docs/backend/lists#list-columns

Remember, not all columns should have field/column definitions, and the two definition files will not necessarily have the same columns specified.

**Comment by ShawnClake** [comment]
@QuinnBast Where is this one at? Have you done any? If so, have you pushed them?

**Comment by QuinnBast** [comment]
How does my update look?

**Comment by ShawnClake** [comment]
@QuinnBast I'm going to close this for now as it looks good. It's quite possible the relations need some tweaking according to: https://octobercms.com/docs/backend/forms#form-fields
