### ISSUE TITLE
Viewing friend list with no friends causes an error

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#86]
When viewing my friend list (I have no friends) I get the following error. Template isn't checking if $friends is null(?)

![image](https://cloud.githubusercontent.com/assets/22599103/23759171/8f3ed37e-04b1-11e7-9dbc-b1ad84407e31.png)

**Comment by ShawnClake** [comment]
@QuinnBast 

Possibly fixed?

**Comment by QuinnBast** [comment]
Unfortunately still getting the error :(

Just realized I didn't include the error message

![image](https://cloud.githubusercontent.com/assets/22599103/23762215/f6af3be4-04ba-11e7-807a-e1b65e9eca36.png)

**Comment by QuinnBast** [comment]
This is solved. However, now that the page is loading, the {% if friends.friendsList %} in the component is not being triggered when you have no friends and the page is loading an empty friend for the first result.

![image](https://cloud.githubusercontent.com/assets/22599103/23768874/0c207f5c-04d3-11e7-87d6-fb2fa91c160b.png)

**Comment by ShawnClake** [comment]
@QuinnBast  Just to be certain, you don't have any friends in the clake_userextended_friends table?

**Comment by QuinnBast** [comment]
I do have some entries in the table but the "accepted" field is 0 for all entires

**Comment by QuinnBast** [comment]
Perfect!
