### ISSUE TITLE
Double friend request won't combine requests

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#89]
Use case:
User 1 sends a request to user 2,
User 2 sends a request to user 1,
There will be 2 entries in the database for friend requests. 

Bug:
The last request in the database will not get updated when accepting a request. 

Steps:
In this case, User 2 can click "Accept" and it will accept and add them as friends and user 1 will show up as a friend for User 2, however, the database will only update the first entry in the database where User 1 sent the request to user 2. Therefore, User 2 will have the friend request in their "friend requests" forever because it will never get updated. This also allows User 2 to be able to friend and unfriend User 1 as they please regardless if User1 wants to be friends or not.

Solution:
Frontend: Don't display a friend request if they are already friends or if a request has already been sent
Backend: Search all pairs in the database, not just the one id in the "sent" or "accept" columns

**Comment by ShawnClake** [comment]
@QuinnBast 

I just tried to reproduce this on my end and I wasn't able to reproduce the error

**Comment by QuinnBast** [comment]
Ah yes. This was a problem on my part, I duplicated some database tables a while back to easily send friend requests from some accounts without being logged in and I must have doubled a request when I duplicated the tables. This can be resolved
