### ISSUE TITLE
Tweaks Before Release

### ISSUE THREAD

**Issue by ShawnClake** [ShawnClake/UserExtended#90]
![image](https://cloud.githubusercontent.com/assets/19659689/23814880/f5d6644a-05aa-11e7-98d1-a65ffc810364.png)

The submit button should be disabled by default, but the red box should not appear by default. Maybe adding display: none; on the style for the red box.

---

![image](https://cloud.githubusercontent.com/assets/19659689/23814909/16d66b04-05ab-11e7-96ec-1d61f362b35a.png)

When no errors remain, the red box should disapear, and the create button should be usable again. Its staying disabled for some reason.

Same problems exist for creating a role

---

![image](https://cloud.githubusercontent.com/assets/19659689/23814967/564b920a-05ab-11e7-9fa4-4bc0ce2e52c3.png)

When editing a group, the save button does not get disabled, and the red boxes do not appear even though both name and code are blank.

---

![image](https://cloud.githubusercontent.com/assets/19659689/23815101/0e24cce8-05ac-11e7-8352-17e3cc1d416f.png)

✔ After a fresh install and adding two users, this happens when trying to search for them

---

✔The add friend option on profiles should not be visible unless a user is logged in.
✔The add friend option on profiles should not be visible if you are visiting your own profile.

✔ Avatar images are not displaying on user profiles

---

![image](https://cloud.githubusercontent.com/assets/19659689/23864464/3bc05cc0-07d8-11e7-8bef-25d572ecd159.png)

✔The error messages should have consistent formatting. Capitals, punctuation etc. 
✔The error messages also appear if I hit tab to enter the field for the first time which is undesirable.

---

![image](https://cloud.githubusercontent.com/assets/19659689/23864725/04c8e0f6-07d9-11e7-8a6f-c24dd696832d.png)

✔Auto filled forms (For example on the login page) result in the signup button still being disabled.

---

![image](https://cloud.githubusercontent.com/assets/19659689/23864853/6f11ce00-07d9-11e7-910d-6a2fad130768.png)

This is the login page.

The box probably shouldn't stretch the width of the entire page. It also extends off the page on the right side.

---

![image](https://cloud.githubusercontent.com/assets/19659689/23864927/a963e336-07d9-11e7-9d05-e1e956c2992a.png)

This is the register page.

The error message should say something more like "You cannot register while already logged in"

**Comment by QuinnBast** [comment]
For the last photo, add 

{% if ueuser.loggedIn() %} after line 27 of search_results.htm and {% endif %} before line 33

**Comment by ShawnClake** [comment]
> For the last photo, add
{% if ueuser.loggedIn() %} after line 27 of search_results.htm and {% endif %} before line 33

Fixed

**Comment by QuinnBast** [comment]
All issues in this thread are solved

**Comment by ShawnClake** [comment]
I'm not sure if the red box bug is actually fixed or not. It's still doing it on mine, but we can reopen this later if need be.
