### ISSUE TITLE
"Random User" doesn't properly link to user profiles

### ISSUE THREAD

**Issue by QuinnBast** [ShawnClake/UserExtended#95]
When clicking on a user's profile in the random user list is creates the following permalink resulting in page not found.
![image](https://cloud.githubusercontent.com/assets/22599103/23961131/99ef0bb4-096f-11e7-9fd1-0e5e397e84c9.png)
![image](https://cloud.githubusercontent.com/assets/22599103/23961157/aa85bd24-096f-11e7-8b3f-bb34ca021c29.png)

But the code is the exact same in the search-results page yet the permalinks work fine there.
![image](https://cloud.githubusercontent.com/assets/22599103/23961110/89c26a74-096f-11e7-8a80-989348b4aa7d.png)
![image](https://cloud.githubusercontent.com/assets/22599103/23961188/c3af36f4-096f-11e7-8bba-14afbf080d86.png)

**Comment by ShawnClake** [comment]
@QuinnBast 

Did you specify a profilePage property on the ueuser component you're using for the random user list?

**Comment by QuinnBast** [comment]
Hehehehe.......
